return {
	require("config.plug.lsp"),
	require("config.plug.cmp"),
	require("config.plug.luasnip"),
	require("config.plug.nvimtree"),
	require("config.plug.gitsigns"),
	require("config.plug.autopairs"),
	require("config.plug.lualine"),
	require("config.plug.bufferline"),
	require("config.plug.nvim-comment"),
	require("config.plug.nvim-treesitter"),
	require("config.plug.indent-blankline"),
	require("config.plug.workspaces"),
	require("config.plug.trailing-whitespace"),
}
